---
include:
  name:
    - l2forwarding.code.p4
integrate:
  - logic: l2forwarding.code.p4
    block: IngressImpl
    controlName: L2forwarding_ing
    callControl: True
    arguments:
      - type: headers_t
        name: hdr
      - type: local_metadata_t
        name: local_metadata
      - type: standard_metadata_t
        name: standard_metadata